version: '3.7'
services:
  e7_in_docker:
   build: .
   environment:
    - PORT=5000
    - REDIS_HOST=redis
    - REDIS_PORT=6379
   ports:
    - 8081:8081
   command: gunicorn -w 4 -b 127.0.0.1:5000 api:app
   depends_on:
    - redis
    - mongo
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    command: redis-server
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
    - /opt/mongo/db:/data/db
    ports:
    - 27017:27017


