version: '3.7'
services:
  flask:
   build: .
   container_name: e7_in_docker
   image: digitalocean.com/flask-python
   restart: unless-stopped
   environment:
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
      MONGODB_HOSTNAME: mongodb
   ports:
    - 5000:5000
   command: gunicorn -w 4 -b 127.0.0.1:5000 api:app
   depends_on:
     - redis
     - mongo

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
       - 27017:27017
volumes:
  mongodbdata:
    driver: local